//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HeadsetPresenter.rc
//
#define IDBACK                          3
#define IDCANCEL2                       3
#define IDTEST                          4
#define IDDOWNLOAD                      5
#define IDCANCEL3                       6
#define IDD_HEADSETPRESENTER_DIALOG     102
#define IDD_HPDIALOG                    104
#define IDR_MAINFRAME                   128
#define IDD_DEVICE_DIALOG               132
#define IDD_WIZARD_DIALOG               134
#define IDD_SERVICE_DIALOG              136
#define IDD_RECONNECT_DIALOG            138
#define IDB_GIRL                        141
#define IDB_INVISIO                     142
#define IDB_JABRA250                    144
#define IDD_MANUAL_SERVICE_DIALOG       145
#define IDD_MODE_DIALOG                 146
#define IDB_NEWLOGO                     148
#define IDD_INFO_DLG                    149
#define IDD_WIZARD_COMPLETED_DIALOG     150
#define IDD_MANUAL_CONNECT_DIALOG       151
#define IDD_SETTINGS_DIALOG             152
#define IDD_AVRCP_DIALOG                153
#define IDD_MANUAL_STACK_SELECTION      154
#define IDI_HP_ICON_MASK                160
#define IDI_HP_ICON                     161
#define IDB_LOGO_64x64                  163
#define IDB_LOGO_50x50                  164
#define IDD_TOSHIBAINFO_DIALOG          165
#define IDB_WHITE_B                     166
#define IDB_GREEN_B                     169
#define IDD_APPLICATION_MANAGER         170
#define IDD_APP_EDIT_DIALOG             173
#define IDD_AUDIO_SELECT                176
#define IDD_MANUAL_PIN_DIALOG           178
#define IDD_PREPARE_PAIRING             179
#define IDD_ACTIVE_CONNECTION_PROBLEM   180
#define IDB_HEADSET_CONNECTED           180
#define IDC_PIN                         1000
#define IDC_DEVICES                     1002
#define IDSTARTSTOP                     1003
#define IDC_OK                          1004
#define IDNEXT                          1006
#define IDC_WIZARD_PROGRESS             1007
#define IDNEXT2                         1007
#define IDC_SERVICES_LIST               1008
#define IDC_STATIC_SERVICE_INFO         1009
#define IDC_WIZARD_PROGRESS_BAR         1010
#define IDC_STATIC_HP_RECONNECT_INFO    1011
#define IDC_BUTTON_START_WIZARD         1012
#define IDC_BUTTON_RECONNECT            1013
#define IDC_STATIC_RECON_INFO           1014
#define IDWIZARD                        1015
#define IDC_BUTTON_STUCK                1016
#define IDC_APPNAME_LISTBOX             1019
#define IDC_STATIC_SELECT_APP           1020
#define IDC_STATIC_WELCOME_MSG          1021
#define IDC_WIZARD_STEP_DEVICESEARCH    1023
#define IDC_BACK                        1024
#define IDC_WIZARD_DEV_INFO             1025
#define IDC_WIZARD_HEADLINE             1026
#define IDC_WIZ_PROGRESS                1027
#define IDC_SERVICE_HEADLINE            1028
#define IDC_CANCEL                      1030
#define IDC_RADIO1                      1031
#define IDC_RADIO2                      1032
#define IDC_MSERVICE_INFO1              1034
#define IDC_MSERVICE_INFO2              1035
#define IDC_RADIO_BLUESOLEIL            1035
#define IDC_MSERVICE_INFO               1036
#define IDC_RADIO_TOSHIBA               1036
#define IDC_RADIO_OTHER                 1037
#define IDC_MODE_INFO1                  1039
#define IDC_MODE_INFO2                  1040
#define IDC_REC_FAIL_HEADER             1041
#define IDC_REC_FAIL_BODY               1042
#define IDC_BUTTON_ADD                  1043
#define IDC_INFO_HEADER                 1044
#define IDC_INFO_SUB_HEADER             1045
#define IDC_INFO_TEXT                   1046
#define IDFINISH                        1047
#define IDC_WIZ_COMP_HEADER             1048
#define IDC_WIZ_COMP_BODY               1049
#define IDC_MANUAL_CON_INFO             1051
#define IDC_NEXT                        1052
#define IDC_MAN_CON_INFO2               1053
#define IDC_BUTTON1                     1054
#define IDAPPLY                         1055
#define IDC_RADIO_REPLUG_1              1056
#define IDC_RADIO_REPLUG_2              1057
#define IDC_RADIO_FB_1                  1058
#define IDC_RADIO_FB_2                  1059
#define IDC_LIST_SLEEP                  1060
#define IDC_RADIO_RESTART_1             1060
#define IDC_LIST_STARTUP                1061
#define IDC_RADIO_RESTART_2             1061
#define IDC_SPEECH                      1062
#define IDC_CHECK_SPEECH_1              1063
#define IDC_CHECK_SPEECH_ACTIVE         1063
#define IDC_CHECK_SPEECH_2              1064
#define IDC_CHECK_VOICE_FEEDBACK        1064
#define IDC_CHECK_SPEECH_3              1065
#define IDC_CHECK_SPEECH_ONLY           1065
#define IDC_STATIC_SPEECH_NOT_INSTALLED 1066
#define IDTRAIN                         1067
#define IDC_SETTINGS_HEADER             1068
#define IDC_CHECK_TEST_MODE             1068
#define IDC_BTN_SETTINGS                1069
#define IDC_AVRCP_HEADLINE              1070
#define IDC_RADIO_AVRCP_1               1071
#define IDC_RADIO_AVRCP_2               1072
#define IDC_RADIO_MICROSOFT             1074
#define IDC_RADIO_WIDCOMM               1075
#define IDC_B_WHITE                     1078
#define IDC_B_GREEN                     1079
#define IDC_EDIT1                       1080
#define IDC_WILDCARD1                   1081
#define IDC_WILDCARD2                   1082
#define IDC_STATIC_VOLUMEUP             1083
#define IDC_STATIC_VOLUMEDOWN           1084
#define IDC_STATIC_VOLUMEDOWN2          1085
#define IDC_CHECK1                      1086
#define IDC_CHECK2                      1087
#define IDC_CHECK3                      1088
#define IDC_CHECK4                      1089
#define IDC_COMBO1                      1090
#define IDC_COMBO2                      1091
#define IDC_CHECK5                      1092
#define IDC_CHECK6                      1093
#define IDC_COMBO3                      1094
#define IDC_STATIC_TEXT1                1098
#define IDC_STATIC_TEXT2                1099
#define IDC_APP_EDIT                    1100
#define IDC_APP_EDIT_STATIC             1101
#define IDC_CHECK_CONFIDENCE            1104
#define IDC_AUDIO_LIST                  1106
#define IDC_STATIC_AUDIO                1107
#define IDC_CHECK_DISP_AGAIN            1110
#define IDC_BTN_RESTORE                 1112
#define IDC_KEEP_ALIVE_LB               1113
#define IDC_EDIT_MANUAL_PIN             1114
#define IDC_STATIC_PIN_MSG              1115
#define IDC_CHECK_DEV_PREP              1116
#define IDC_STATIC_DEV_PREP             1117
#define IDC_HS_CONNECTED                1118
#define IDC_STATIC_EXISTING_CONNECTION_MSG 1119

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1120
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
